CREATE TABLE  IF NOT EXISTS tasks (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(1000) NOT NULL CHECK (LENGTH(name) BETWEEN 2 AND 1000),
type VARCHAR(256) NOT NULL,
importance VARCHAR(256) NOT NULL,
start_time TIMESTAMP ,
finish_time TIMESTAMP ,
description VARCHAR(1000),
status VARCHAR(10) NOT NULL CHECK (status IN('ToDO','InProgress','Done'))
)